name: renpy_ubuntu

services:
  renpy:
    build:
      args:
        - DESIRED_LOCALE=${LOCALE}
        - DESIRED_SUBLOCALE=${SUBLOCALE}
      context: ../
      dockerfile: ./ubuntu/ubuntu.dockerfile
    container_name: renpy_ubuntu
    volumes:
      - ${DOCKER_MOUNT}
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=host.docker.internal:0.0
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
