name: renpy_proofreading

services:
  proofreader:
    image: elestio/languagetool:latest
    container_name: languagetool
    ports:
      - ${MAPPED_PORT}:${MAPPED_PORT}
    stdin_open: false
    tty: false
    environment:
      - langtool_languageModel=/ngrams
      # - langtool_fasttextBinary=/usr/bin/fasttext
      # - langtool_fasttextModel=/fasttext-model.bin
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - ${DOCKER_MOUNT}
