name: renpy_fedora

services:
  renpy:
    build:
      args:
        - DESIRED_LOCALE=${LOCALE}
        - DESIRED_SUBLOCALE=${SUBLOCALE}
      context: ../
      dockerfile: ./fedora/fedora_glx_xdg.dockerfile
    container_name: renpy_fedora
    volumes:
      - ${DOCKER_MOUNT}
    environment:
      - DISPLAY=host.docker.internal:0.0
    network_mode: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
